### PR TITLE
fix: bump bubbletea to 1.1.2 to build with ansi 0.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
👋 seeing some build issue with the latest release as below:

```
# github.com/charmbracelet/bubbletea
  /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/standard_renderer.go:279:24: undefined: ansi.MoveCursor
  /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/standard_renderer.go:316:17: undefined: ansi.MoveCursorOrigin
  /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/standard_renderer.go:346:17: undefined: ansi.MoveCursorOrigin
  /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/standard_renderer.go:519:24: undefined: ansi.MoveCursor
  /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/standard_renderer.go:556:23: undefined: ansi.MoveCursor
  /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/standard_renderer.go:562:23: undefined: ansi.MoveCursor
  /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/standard_renderer.go:583:23: undefined: ansi.MoveCursor
  /home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/charmbracelet/bubbletea@v1.1.1/standard_renderer.go:5[88](https://github.com/Homebrew/homebrew-core/actions/runs/11505864250/job/32028742807?pr=195469#step:4:89):23: undefined: ansi.MoveCursor
```

relates to https://github.com/Homebrew/homebrew-core/pull/195469

### CODE REVIEW

**Comment by dvaumoron** [comment]
Yes, happily they fixed the issue with this 1.1.2

Thanks
